# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 13
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Archive production artifact
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: _site
  textile_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download production artifact
        uses: actions/download-artifact@v1
        with:
          name: _site
      - name: Bucket push action
        id: push
        uses: textileio/github-action-bucket-push@master
        with:
          bucket: ${{ env.BUCKET }}
          path: _site
          key: ${{ secrets.TEXTILE_KEY }}
          secret: ${{ secrets.TEXTILE_SECRET }}
          thread: ${{ env.THREAD }}
      - run: echo "bucket - ${{ steps.bucket.outputs.bucket }}"
      - run: echo "ipfs - ${{ steps.bucket.outputs.ipfs }}"
      - run: echo "ipfs link - ${{ steps.bucket.outputs.ipfsUrl }}"
      - run: echo "ipns - ${{ steps.bucket.outputs.ipns }}"
      - run: echo "ipns link - ${{ steps.bucket.outputs.ipnsUrl }}"
      - run: echo "hub - ${{ steps.bucket.outputs.hub }}"
      - run: echo "www - ${{ steps.bucket.outputs.www }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download production artifact
      uses: actions/download-artifact@v1
      with:
        name: _site
    - name: Deploy to IPFS
      uses: aquiladev/ipfs-action@v0.1.2-alpha
      id: upload
      with:
        path: ./_site
        verbose: true
