# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 13
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: aquiladev/ipfs-action@v0.1.1
      id: upload
      with:
        path: ./_site
