# This is a basic workflow to help you get started with Actions

name: IPFS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: aquiladev/ipfs-action@v1
      id: upload
      with:
        path: ./_site
