name: bucket_publish
on:
  push:
    branches:
      - master
jobs:
  bucket_publish:
    env:
      BUCKET: 'etnobotanik'
      THREAD: 'bafkv3rhaamn56x77276lddjifcieakxbydi6giqmpux6yzz6k345wqy'
    runs-on: ubuntu-latest
    name: Create a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 13
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 13
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket: '${{ env.BUCKET }}'
        path: './_site'
        key: ${{ secrets.TEXTILE_KEY }}
        secret: ${{ secrets.TEXTILE_SECRET }}
        thread: '${{ env.THREAD }}'
    # Use the output from the `hello` step
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Get the Bucket URL
      run: echo "The Bucket URL is ${{ steps.push.outputs.url }}"